language: php

php:
    - 8.0
    - 8.1
    - 8.2
    - hhvm

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
    allow_failures:
        - php: 8.0
        - php: 8.1
        - php: 8.2
        - php: hhvm
    fast_finish: true

notifications:
    on_success: never
    on_failure: always
